// Seed data for BeakBuddy database
import { Species, FoodItem } from '../types';
import { comprehensiveFoodData } from '../data/foodSafety';

// 50 Parrot Species (exact list as specified)
export const speciesSeedData: Omit<Species, 'id'>[] = [
    { commonName: 'Budgerigar (Budgie)', scientificName: 'Melopsittacus undulatus', popularityRank: 1, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'budgerigar.png' },
    { commonName: 'Cockatiel', scientificName: 'Nymphicus hollandicus', popularityRank: 2, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'cockatiel.png' },
    { commonName: 'African Grey', scientificName: 'Psittacus erithacus', popularityRank: 3, sizeCategory: 'Medium', sensitivityTag: 'Sensitive', imageAsset: 'african-grey.png' },
    { commonName: 'Green-cheeked Conure', scientificName: 'Pyrrhura molinae', popularityRank: 4, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'green-cheeked-conure.jpg' },
    { commonName: 'Sun Conure', scientificName: 'Aratinga solstitialis', popularityRank: 5, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'sun-conure.png' },
    { commonName: 'Quaker Parrot (Monk Parakeet)', scientificName: 'Myiopsitta monachus', popularityRank: 6, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'monk-parakeet.png' },
    { commonName: 'Lovebird', scientificName: 'Agapornis', popularityRank: 7, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'lovebird.png' },
    { commonName: 'Conure (General)', scientificName: 'Aratinga/Pyrrhura', popularityRank: 8, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'generic.png' },
    { commonName: 'Macaw (General)', scientificName: 'Ara', popularityRank: 9, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'generic.png' },
    { commonName: 'Amazon Parrot (General)', scientificName: 'Amazona', popularityRank: 10, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'generic.png' },
    { commonName: 'Cockatoo (General)', scientificName: 'Cacatuidae', popularityRank: 11, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'generic.png' },
    { commonName: 'Eclectus', scientificName: 'Eclectus roratus', popularityRank: 12, sizeCategory: 'Medium', sensitivityTag: 'Sensitive', imageAsset: 'eclectus-parrot.png' },
    { commonName: 'Caique', scientificName: 'Pionites', popularityRank: 13, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'white-bellied-caique.png' },
    { commonName: 'Senegal Parrot', scientificName: 'Poicephalus senegalus', popularityRank: 14, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'senegal-parrot.png' },
    { commonName: 'Indian Ringneck', scientificName: 'Psittacula krameri', popularityRank: 15, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'ring-necked-parakeet.png' },
    { commonName: 'Parrotlet', scientificName: 'Forpus', popularityRank: 16, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'pacific-parrotlet.png' },
    { commonName: 'Blue and Gold Macaw', scientificName: 'Ara ararauna', popularityRank: 17, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'blue-gold-macaw.png' },
    { commonName: 'Scarlet Macaw', scientificName: 'Ara macao', popularityRank: 18, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'scarlet-macaw.png' },
    { commonName: 'Greenwing Macaw', scientificName: 'Ara chloropterus', popularityRank: 19, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'generic.png' },
    { commonName: 'Hyacinth Macaw', scientificName: 'Anodorhynchus hyacinthinus', popularityRank: 20, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'hyacinth-macaw.png' },
    { commonName: 'Military Macaw', scientificName: 'Ara militaris', popularityRank: 21, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'generic.png' },
    { commonName: 'Yellow-naped Amazon', scientificName: 'Amazona auropalliata', popularityRank: 22, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'yellow-naped-amazon.png' },
    { commonName: 'Blue-fronted Amazon', scientificName: 'Amazona aestiva', popularityRank: 23, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'blue-fronted-amazon.png' },
    { commonName: 'Double Yellow-headed Amazon', scientificName: 'Amazona oratrix', popularityRank: 24, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'double-yellow-headed-amazon.png' },
    { commonName: 'Orange-winged Amazon', scientificName: 'Amazona amazonica', popularityRank: 25, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'generic.png' },
    { commonName: 'Umbrella Cockatoo', scientificName: 'Cacatua alba', popularityRank: 26, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'umbrella-cockatoo.png' },
    { commonName: 'Moluccan Cockatoo', scientificName: 'Cacatua moluccensis', popularityRank: 27, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'moluccan-cockatoo.png' },
    { commonName: 'Goffin Cockatoo', scientificName: 'Cacatua goffiniana', popularityRank: 28, sizeCategory: 'Medium', sensitivityTag: 'Sensitive', imageAsset: 'goffins-cockatoo.png' },
    { commonName: 'Sulphur-crested Cockatoo', scientificName: 'Cacatua galerita', popularityRank: 29, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'sulphur-crested-cockatoo.jpg' },
    { commonName: 'Galah (Rose-breasted Cockatoo)', scientificName: 'Eolophus roseicapilla', popularityRank: 30, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'galah-cockatoo.jpg' },
    { commonName: 'Jenday Conure', scientificName: 'Aratinga jandaya', popularityRank: 31, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'jenday-conure.jpg' },
    { commonName: 'Nanday Conure', scientificName: 'Aratinga nenday', popularityRank: 32, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'nanday-conure.jpg' },
    { commonName: 'White-bellied Caique', scientificName: 'Pionites leucogaster', popularityRank: 33, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'white-bellied-caique.png' },
    { commonName: 'Black-headed Caique', scientificName: 'Pionites melanocephalus', popularityRank: 34, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'black-headed-caique.png' },
    { commonName: 'Alexandrine Parakeet', scientificName: 'Psittacula eupatria', popularityRank: 35, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'alexandrine-parakeet.png' },
    { commonName: 'Crimson Rosella', scientificName: 'Platycercus elegans', popularityRank: 36, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'crimson-rosella.jpg' },
    { commonName: 'Eastern Rosella', scientificName: 'Platycercus eximius', popularityRank: 37, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'eastern-rosella.jpg' },
    { commonName: 'Rainbow Lorikeet', scientificName: 'Trichoglossus moluccanus', popularityRank: 38, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Rainbow_lorikeet_%28Trichoglossus_moluccanus%29.jpg' },
    { commonName: 'Scaly-breasted Lorikeet', scientificName: 'Trichoglossus chlorolepidotus', popularityRank: 39, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Scaly-breasted_Lorikeet_-_Centenary_Lakes.jpg' },
    { commonName: 'Pionus (General)', scientificName: 'Pionus', popularityRank: 40, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Blue-headed_Parrot_%28Pionus_menstruus%29_-on_perch.jpg' },
    { commonName: 'White-capped Pionus', scientificName: 'Pionus senilis', popularityRank: 41, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'white-capped-pionus.jpg' },
    { commonName: 'Blue-headed Pionus', scientificName: 'Pionus menstruus', popularityRank: 42, sizeCategory: 'Medium', sensitivityTag: 'Normal', imageAsset: 'blue-headed-pionus.png' },
    { commonName: 'Palm Cockatoo', scientificName: 'Probosciger aterrimus', popularityRank: 43, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Probosciger_aterrimus_-Singapore_Zoo-8a.jpg' },
    { commonName: 'Kea', scientificName: 'Nestor notabilis', popularityRank: 44, sizeCategory: 'Large', sensitivityTag: 'Sensitive', imageAsset: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Kea_in_Fiordland.jpg' },
    { commonName: 'Yellow-crowned Kakariki', scientificName: 'Cyanoramphus auriceps', popularityRank: 45, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'yellow-crowned-kakariki.jpg' },
    { commonName: 'Red-crowned Kakariki', scientificName: 'Cyanoramphus novaezelandiae', popularityRank: 46, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'red-crowned-kakariki.jpg' },
    { commonName: 'Lineolated Parakeet', scientificName: 'Bolborhynchus lineola', popularityRank: 47, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'lineolated-parakeet.png' },
    { commonName: 'Bourke Parakeet', scientificName: 'Neopsephotus bourkii', popularityRank: 48, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'bourkes-parakeet.jpg' },
    { commonName: 'Brown-throated Conure', scientificName: 'Eupsittula pertinax', popularityRank: 49, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Aratinga_pertinax_-national_park_-Aruba-8.jpg' },
    { commonName: "Meyer's Parrot", scientificName: 'Poicephalus meyeri', popularityRank: 50, sizeCategory: 'Small', sensitivityTag: 'Normal', imageAsset: 'meyers-parrot.png' },
];

// Export the comprehensive food database
export const foodSeedData = comprehensiveFoodData;
